### ISSUE TITLE
使用的时候出现报错:输入的维度无效

### ISSUE THREAD

**Issue by DMB-codegang** [nkxingxh/yolox-onnx-api-server#2]
容器环境：
    libgl1-mesa-glx
    libglib2.0-0
    libsm6
    libxrender1
    libxext6

python:3.10.15
yolox-onnx-api-server
flask==3.0.3
numpy==1.26.3
onnxruntime==1.19.2
opencv-python==4.9.0.80
waitress==3.0.2

[nailong_v2.6_tiny.onnx](https://github.com/nkxingxh/NailongDetection)

报错信息：
```
ERROR:server:Exception on /predict [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/app/server.py", line 192, in predict
    output = session.run(None, ort_inputs)
  File "/usr/local/lib/python3.10/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 220, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: images for the following indices
 index: 2 Got: 640 Expected: 416
 index: 3 Got: 640 Expected: 416
 Please fix either the inputs/outputs or the model.
```

**Comment by DMB-codegang** [comment]
另附 dockerfile ：
```
FROM python:3.10.15

# 设置环境变量
ARG NAME
ENV NAME=${NAME}

# 设置工作目录
WORKDIR /app

# 复制 requirements.txt 并安装 Python 包
COPY ./app/requirements.txt /app/
RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple/ -r requirements.txt

# 复制应用代码到镜像中的 /app 目录
COPY ./app /app

# 创建 /etc/apt/sources.list 文件并写入默认内容
RUN echo "deb http://deb.debian.org/debian bookworm main contrib non-free" > /etc/apt/sources.list && \
    echo "deb http://deb.debian.org/debian bookworm-updates main contrib non-free" >> /etc/apt/sources.list && \
    echo "deb http://security.debian.org/debian-security bookworm-security main contrib non-free" >> /etc/apt/sources.list

# 更换为清华大学的镜像源
RUN sed -i 's|http://deb.debian.org/debian|https://mirrors.tuna.tsinghua.edu.cn/debian|g' /etc/apt/sources.list && \
    sed -i 's|http://security.debian.org/debian-security|https://mirrors.tuna.tsinghua.edu.cn/debian-security|g' /etc/apt/sources.list && \
    apt-get update && \
    apt-get upgrade -y

# 安装OpenCV所需的依赖
RUN apt-get install -y \
    libgl1-mesa-glx \
    libglib2.0-0 \
    libsm6 \
    libxrender1 \
    libxext6 \
    && rm -rf /var/lib/apt/lists/*

# 设置容器启动命令
CMD ["python", "server.py", "-m", "nailong_v2.6_tiny.onnx", "-l", "labels.txt"]
```

**Comment by nkxingxh** [comment]
没有指定正确的模型尺寸。默认的尺寸为`416,416`，你需要修改为实际模型的尺寸。

```
-i INPUT_SHAPE, --input_shape INPUT_SHAPE
                        指定推理的输入形状。
```
